-- no workhsop items, comes as an example

local gem_spawn = {
  "luxor_gems/lux1_spawn_gem.ogg",

  "luxor_gems/lux2_spawn_gem_1.ogg",
  "luxor_gems/lux2_spawn_gem_2.ogg",
  "luxor_gems/lux2_spawn_gem_3.ogg",

  "luxor_gems/lux3_spawn_gem_1.ogg",
  "luxor_gems/lux3_spawn_gem_2.ogg",
  "luxor_gems/lux3_spawn_gem_3.ogg",
}
local gem_collect = {
  "luxor_gems/lux2_catch_gem.ogg",
  "luxor_gems/lux3_catch_gem.ogg",
}

-- TODO: make the treasures resize based on their sprite dimensions
LotsOfCurrency.RegisterDenomination(
  "luxor_gems",
  {
    ents = {
      "luxor_treasure_rainbowgem",

      "luxor_treasure_sungem",
      "luxor_treasure_purpleramidgem",

      "luxor_treasure_chaosdrivegem",
      "luxor_treasure_coughdropgem",
      "luxor_treasure_cubegem",
      "luxor_treasure_cyangem",
      "luxor_treasure_diamondgem",
      "luxor_treasure_greennuggetgem",
      "luxor_treasure_hamburgergem",
      "luxor_treasure_manifoldgem",
      "luxor_treasure_orangegem",
      "luxor_treasure_rubygem",
      "luxor_treasure_teardropgem",
      "luxor_treasure_trianglegem",

      "luxor_treasure_crown",
      "luxor_treasure_bracelet",
      "luxor_treasure_rgbarrel",
      "luxor_treasure_ring",
      "luxor_treasure_scarab",

      "luxor_treasure_ankhcoin4",
      "luxor_treasure_ankhcoin3",
      "luxor_treasure_ankhcoin2",
      "luxor_treasure_ankhcoin1",
    },
    values = {
      79,

      73,
      71,

      67,
      61,
      59,
      53,
      47,
      43,
      41,
      37,
      31,
      29,
      23,
      19,

      17,
      13,
      11,
      7,
      5,

      4,
      3,
      2,
      1,
    },
  },
  {
    luxor_treasure_rainbowgem = {
      PrintName = "Rainbow Gem",
      Worth = 79,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_rainbowgem",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },
    luxor_treasure_sungem = {
      PrintName = "Sun Gem",
      Worth = 73,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_sungem",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },
    luxor_treasure_purpleramidgem = {
      PrintName = "Pyramid Gem",
      Worth = 71,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_purpleramidgem",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },

    luxor_treasure_chaosdrivegem = {
      PrintName = "Pink Gem",
      Worth = 67,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_chaosdrivegem",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },
    luxor_treasure_coughdropgem = {
      PrintName = "Yellow Gem",
      Worth = 61,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_coughdropgem",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },
    luxor_treasure_cubegem = {
      PrintName = "Green Gem",
      Worth = 59,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_cubegem",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },
    luxor_treasure_cyangem = {
      PrintName = "Cyan Gem",
      Worth = 53,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_cyangem",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },
    luxor_treasure_diamondgem = {
      PrintName = "White Gem",
      Worth = 47,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_diamondgem",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },
    luxor_treasure_greennuggetgem = {
      PrintName = "Green Gem",
      Worth = 43,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_greennuggetgem",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },
    luxor_treasure_hamburgergem = {
      PrintName = "Amber Gem",
      Worth = 41,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_hamburgergem",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },
    luxor_treasure_manifoldgem = {
      PrintName = "Lime Gem",
      Worth = 37,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_manifoldgem",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },
    luxor_treasure_orangegem = {
      PrintName = "Orange Gem",
      Worth = 31,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_orangegem",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },
    luxor_treasure_ruby = {
      PrintName = "Red Gem",
      Worth = 29,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_ruby",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },
    luxor_treasure_teardropgem = {
      PrintName = "Blue Gem",
      Worth = 23,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_teardropgem",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },
    luxor_treasure_trianglegem = {
      PrintName = "Violet Gem",
      Worth = 19,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_trianglegem",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },

    luxor_treasure_crown = {
      PrintName = "Treasure Crown",
      Worth = 17,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_crown",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },
    luxor_treasure_bracelet = {
      PrintName = "Treasure Necklace",
      Worth = 13,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_bracelet",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },
    luxor_treasure_rgbarrel = {
      PrintName = "Treasure Bracelet",
      Worth = 11,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_rgbarrel",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },
    luxor_treasure_ring = {
      PrintName = "Treasure Ring",
      Worth = 7,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_ring",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },
    luxor_treasure_scarab = {
      PrintName = "Treasure Scarab",
      Worth = 5,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_scarab",
      SpawnNoises	= gem_spawn,
      CollectNoises	= gem_collect,
      HullSize = 32,
    },

    luxor_treasure_ankhcoin4 = {
      PrintName = "Ankh Coin 4",
      Worth = 4,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_ankhcoin4",
      CollectNoises = {"luxor_gems/lux2_catch_coin.ogg"},
      SpawnNoises = {"luxor_gems/lux2_spawn_coin.ogg"},
      HullSize = 16,
    },
    luxor_treasure_ankhcoin3 = {
      PrintName = "Ankh Coin 3",
      Worth = 3,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_ankhcoin3",
      CollectNoises = {"luxor_gems/lux3_catch_coin.ogg"},
      SpawnNoises = {"luxor_gems/lux3_spawn_coin.ogg"},
      HullSize = 16,
    },
    luxor_treasure_ankhcoin2 = {
      PrintName = "Ankh Coin 2",
      Worth = 2,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_ankhcoin2",
      CollectNoises = {"luxor_gems/lux2_catch_coin.ogg"},
      SpawnNoises = {"luxor_gems/lux2_spawn_coin.ogg"},
      HullSize = 16,
    },
    luxor_treasure_ankhcoin1 = {
      PrintName = "Ankh Coin 1",
      Worth = 1,
      SpriteMaterial = "sprites/luxor_treasures/luxor_treasure_ankhcoin1",
      CollectNoises = {"luxor_gems/lux1_spawn_coin.ogg"},
      SpawnNoises = {"luxor_gems/lux1_spawn_coin.ogg"},
      HullSize = 16,
    },
  }
)
